estimate fee should use correct version
keep-starknet-strange/madara pull request #1051
Opened 2023-08-29 12:51 UTC by gaetbout

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behaviour?

Estimate_fee accepts any version.

Resolves: #991 

## What is the new behaviour?

Estimate_fee should only accept the correct version according to: 
https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/Blocks/transactions/

## Does this introduce a breaking change?

Yes, all application should now use the correct version when estimating a transaction

## Other information

Some tx version are/will be deprecated in the future. It should be updated accordingly.

2023-08-29 14:29 UTC, gaetbout commented
Can't assign any reviewer, so just pinging @tdelabro

2023-08-30 13:52 UTC, tdelabro requested changes

2023-08-30 14:02 UTC, gaetbout commented on CHANGELOG.md
> +- fix: estimate_fee should make sure all transaction have a version being
Moved

2023-08-30 14:03 UTC, gaetbout commented on crates/pallets/starknet/src/tests/declare_tx.rs
> +        transaction.is_query = false;
Indeed, my bad, fixed!

2023-08-30 14:03 UTC, gaetbout commented on docs/faucet-setup.md
> +  const version = "0x100000000000000000000000000000001";
Woopsie, reverted :D

2023-08-30 14:22 UTC, tdelabro approved these changes

2023-08-30 14:41 UTC, merged