Feature/e2e rust tests
keep-starknet-strange/madara pull request #1063
Opened 2023-09-04 06:59 UTC by 0xAsten

Add test cases for getTransactionByBlockIdAndIndex.

Parent issue: https://github.com/keep-starknet-strange/madara/issues/904

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

Rust impl for test get_transaction_by_block_id_and_index:

 - Return an error for a nonexisting block
 - Return an error for an out of block index
 - Compare with getBlockWithTx and make sure order is the same

## Does this introduce a breaking change?

No

## Other information

2023-09-04 12:06 UTC, tdelabro requested changes

2023-09-04 12:06 UTC, tdelabro commented on starknet-rpc-test/get_transaction_by_blockid_and_index.rs
> +    let madara = MadaraClient::new(ExecutionStrategy::Native).await;
Use the test fixture instead (take inspiration from other files)

2023-09-04 12:06 UTC, tdelabro commented on starknet-rpc-test/get_transaction_by_blockid_and_index.rs
> +    let madara = MadaraClient::new(ExecutionStrategy::Native).await;
fixture

2023-09-04 12:06 UTC, tdelabro commented on starknet-rpc-test/get_transaction_by_blockid_and_index.rs
> +    let madara = MadaraClient::new(ExecutionStrategy::Native).await;
fixture

2023-09-04 12:06 UTC, tdelabro commented on starknet-rpc-test/get_transaction_by_blockid_and_index.rs
> +    let execution_2 = execution_2.max_fee(FieldElement::from_hex_be("0xDEADB").expect("Invalid Fee Amount"));
You know it will be a valid fee amount, so you can just unwrap

2023-09-04 12:06 UTC, tdelabro commented on starknet-rpc-test/get_transaction_by_blockid_and_index.rs
> +
You should also compare tx_1 and tx_2 with your input.
Here `get_transaction_by_block_id_and_index` and `get_block_with_txs` could both be bugged in the same way and we wouldn't know

2023-09-04 14:54 UTC, closed without merging

2023-09-05 02:34 UTC, 0xAsten commented
@tdelabro Hi, I opened a new PR because of rebase
https://github.com/keep-starknet-strange/madara/pull/1067

2023-09-05 09:31 UTC, tdelabro commented
The way to go is usually to rebase and then push force, it allows us to keep the history of the comments :)