chore: upgrade class hash in genesis config
keep-starknet-strange/madara pull request #1079
Opened 2023-09-09 11:02 UTC by ayushtom

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2023-09-09 11:02 UTC, ayushtom commented
closes #1049

2023-09-09 12:14 UTC, ayushtom commented
@tdelabro can you review these changes?

2023-09-10 06:22 UTC, tdelabro requested changes
I thought those values also exit as hardcoded constants somewhere in the Rust code. Maybe I'm wrong, can you double check tho

2023-09-10 06:22 UTC, tdelabro commented on CHANGELOG.md
> +- chore: add real class hash values for genesis config
Goes under the `next release` section

2023-09-15 20:20 UTC, ayushtom commented on CHANGELOG.md
> +- chore: add real class hash values for genesis config
done

2023-09-15 20:49 UTC, ayushtom commented
> I thought those values also exit as hardcoded constants somewhere in the Rust code. Maybe I'm wrong, can you double check tho

I think i see that rust code normally serialises this json and reads value from there. These values were not hardcoded in rust code implementation.

2023-09-15 20:50 UTC, ayushtom commented
> I thought those values also exit as hardcoded constants somewhere in the Rust code. Maybe I'm wrong, can you double check tho

I think i see that rust code normally serialises this json and reads value from there. These values were not hardcoded in rust code implementation. @tdelabro

2023-09-16 13:08 UTC, tdelabro approved these changes

2023-09-16 13:09 UTC, merged