RPC cache
keep-starknet-strange/madara pull request #1083
Opened 2023-09-10 20:13 UTC by tchataigner

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

In the current implementation of the madara client, we fetch block data by going through the generated logs of our pallet. As the block data is important and we need fast retrieval, it seems important to:
- Properly store the block data in a dedicated `StorageValue` in our pallet
- When possible retrieve the block data through storage query instead of digest API
- Add a cache layer on top of it to ease retrieval of recurrent queried data

Resolves: #947

## What is the new behavior?

Right now, the update to the code base are as follow:
- Added a `CurrentBlock` type in the starknet pallet, representing a `StorageValue` containing our block data. Also added a getter to retrieve it through our runtime API.
- Added necessary method over our storage implementation to both retrieve the data through the runtime API and directly from our storage.
- Implemented a base LRUCache limited by allocated memory, along with an asynchronous task responsible for the handling of the cache and retrieving data.
- Updated the necessary calls in our RPC implementation, to use the cache task instead of directly retrieving the block data through our logs.
-  Added an argument over the run command to set the allocated memory size limit for the cache.

The new flow is:
1. Run a madara run while specifying `--starknet-log-block-cache-size`. For now, the default value is 200 (most likely will cache little if not nothing)
2. On RPC call, we will send the requested block hash to our data cache task.
3. If the data cache has the block, returns it.
4. Otherwise, we will directly query our storage for it.

## Does this introduce a breaking change?

No

## Other information

Original issue: #947

2023-09-11 09:52 UTC, tchataigner commented
Hey @tdelabro, here is a first draft for the RPC cache. 

As we discussed under the issue, I've implemented the cache to work with allocated memory size instead of values size to make it more precise.

Right now, it seems to fail integration test, which is strange as it passes on my computer. I'll look into it.

The only problem that I have is that I think the benchmark tests to evaluate the cache efficiency are not there. I wanted to add some to try and measure it but I'm having trouble in identifying how to pull that off.

 Could I ask for your input on that ? Ideally, I think that we want to try and spam a request on loop to our RPC methods that concern block fetch (e.g.: `getblockWithTxHashes`)

2023-09-12 14:33 UTC, EvolveArt requested changes
left few comments

2023-09-12 14:33 UTC, EvolveArt commented on crates/client/rpc/src/cache/lru_cache.rs
> +        // succesful but first item should be removed from cache.
```suggestion
        // successful but first item should be removed from cache.
```

2023-09-12 14:33 UTC, EvolveArt commented on crates/client/rpc/src/cache/lru_cache.rs
> +mod tests {
is there a way we can add tests for the metrics too?

2023-09-12 14:33 UTC, EvolveArt commented on crates/client/rpc/src/cache/mod.rs
> +    cache: LRUCache<<B as BlockT>::Hash, T>,
not sure we need to use this hasher here tho, we should probably optimize for performance here w/ blake2

2024-08-02 18:39 UTC, tdelabro commented
repository archived in favor of https://github.com/madara-alliance/madara

2024-08-02 18:39 UTC, closed without merging