Wrapped to wrapper block maping + rpc
keep-starknet-strange/madara pull request #125
Opened 2023-03-30 23:02 UTC by tdelabro

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

No RPC server for starknet pallet

# What is the new behavior?

- a rpc server for starknet pallet
- storing block during the on_finalize execution also add a log to the digest
- the digest is read by a new syncing process that stores a mapping from starknet block hashes to substrate block hashes in a new database. This allows a O(1) complexity when calling the RPC server using the starknet hash.
- an override functionality has also been introduced. It allow to query the storage directly, without using the runtime API, while retaining the ability to fallback on it if needed.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

2023-03-31 06:00 UTC, abdelhamidbakhta requested changes
Left some comments. Most of them are about missing Rust doc. Basically please add Rust doc in all added struct, traits, functions with the conventions we use in the codebase. I feel a bit bad with the facts that there are no tests but I understand they are not trivial to implement and we have a short time to meet the deadline for our demo goal. I am enclined to accept the PR with the missing tests but please add an issue about adding them later. Also I would love if you could do a live walkthrough on this PR to explain the architecture. I think it would be super useful content for new contributors that are not yet familiar with substrate.

2023-04-02 11:43 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +pub fn frontier_database_dir(db_config_dir: &Path, db_path: &str) -> PathBuf {
✅

2023-04-02 11:43 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +    pub fn open(database: &DatabaseSource, db_config_dir: &Path) -> Result<Self, String> {
✅

2023-04-02 11:43 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +    pub fn new(config: &DatabaseSettings) -> Result<Self, String> {
not public anymore

2023-04-02 11:44 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +    pub fn mapping(&self) -> &Arc<MappingDb<Block>> {
✅

2023-04-02 18:32 UTC, tdelabro commented on crates/client/db/src/mapping_db.rs
> +pub struct TransactionMetadata<Block: BlockT> {
removed so no need for comments

2023-04-02 18:33 UTC, tdelabro commented on crates/client/db/src/mapping_db.rs
> +        // TODO: add back when transaction support
✅ 
no even sure we need it. Will confirm while unrolling the RPCs

2023-04-02 19:20 UTC, tdelabro commented on crates/node/Cargo.toml
> +mc-db = { path = "../client/db" }
✅

2023-04-02 19:43 UTC, tdelabro commented
I think it's ready for another review.
I added a lot of doc comments.
I agree with the lack of tests. The thing is that there are no tests for those things in Frontier either. Given that I mostly copy-pasted their code, I am confident it will work. Moreover, it does work when I run the chain. Adding tests on some of those crates could be an interesting first issue for somebody who wants to discover the codebase and the RPC flow.

I would be more than happy to do a live stream where I explain the RPC flow and the reason for those multiple crates to the project contributors. I will ask on the telegram channel if some would be interested and at what time.

2023-04-03 10:20 UTC, abdelhamidbakhta commented on crates/client/db/src/mapping_db.rs
> +        // TODO: add back when transaction support
let me know about it so that I can close this conversation

2023-04-03 10:50 UTC, abdelhamidbakhta approved these changes
lgtm

2023-04-03 17:16 UTC, merged