Apply state diffs
keep-starknet-strange/madara pull request #136
Opened 2023-03-31 16:36 UTC by LucasLvy

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [x] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: Fixes #90 

# What is the new behavior?

- Apply state diffs to substrate storage

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

2023-04-03 17:15 UTC, abdelhamidbakhta requested changes
left some comments

2023-04-03 17:15 UTC, abdelhamidbakhta commented on crates/pallets/starknet/src/lib.rs
> +        pub fn apply_state_diffs(state: &CachedState<DictStateReader>) -> Result<(), StateDiffError> {
please add rust doc

2023-04-03 17:15 UTC, abdelhamidbakhta commented on crates/pallets/starknet/src/lib.rs
> +        pub fn apply_state_diffs(state: &CachedState<DictStateReader>) -> Result<(), StateDiffError> {
please add comments inside the function explaining the different steps

2023-04-03 17:36 UTC, EvolveArt requested changes

2023-04-03 17:36 UTC, EvolveArt commented on crates/primitives/starknet/src/transaction/types.rs
> +/// Error enum wrapper for events.
wrong comment

2023-04-03 17:50 UTC, LucasLvy commented on crates/pallets/starknet/src/tests.rs
> +        // Cannot declare a class with None
You mean explain what a selector is ?

2023-04-03 17:51 UTC, LucasLvy commented on crates/primitives/starknet/src/execution/mod.rs
> +impl From<&starknet_api::state::ContractClass> for ContractClassWrapper {
it was to stay coherent with the one above but sure can switch

2023-04-03 17:53 UTC, EvolveArt commented on crates/pallets/starknet/src/tests.rs
> +        // Cannot declare a class with None
No just what function name does it refer to

2023-04-03 17:53 UTC, EvolveArt commented on crates/primitives/starknet/src/execution/mod.rs
> +impl From<&starknet_api::state::ContractClass> for ContractClassWrapper {
Alright well if you could switch both would be awesome

2023-04-03 18:18 UTC, LucasLvy commented on crates/primitives/starknet/src/execution/mod.rs
> +impl From<&starknet_api::state::ContractClass> for ContractClassWrapper {
wasn't used so removed it

2023-04-03 20:24 UTC, EvolveArt approved these changes

2023-04-04 12:56 UTC, abdelhamidbakhta approved these changes
lgtm

2023-04-04 12:57 UTC, merged