Refactoring: Rename LAST_SYNCED_L1_BLOCK to be more clear
keep-starknet-strange/madara pull request #1361
Opened 2024-01-09 19:44 UTC by dangush

# Refactor

Closes Issue #1335 by refactoring LAST_SYNCED_L1_BLOCK to a struct named LastSyncedEventBlock which contains a block_number field and event_index field. 

## What is the current behavior?

When `process_l1_message` is called, the L1 block number is written to the MessagingDb. 

Resolves: #1335 

## What is the new behavior?

When `process_l1_message` is called, a struct containing both the L1 block number and event_index is written to the MessagingDb. 

-
-
-

## Does this introduce a breaking change?

I'm not yet sure if/how the MessagingDb schema needs to be changed to accept the encoded Struct instead of previously-encoded u64 value. Accorrding to the [SCALE encoding docs](https://docs.substrate.io/reference/scale-codec/) I believe structs get encoded as a vector of bytes, so I assume that a value twice the current size will need to be written to the DB.

2024-01-12 08:47 UTC, apoorvsadana approved these changes
lgtm

2024-01-17 09:24 UTC, apoorvsadana commented
@tdelabro can you review this once?

2024-01-17 10:53 UTC, tdelabro requested changes

2024-01-17 10:53 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +pub mod messaging_db;
We don't want any of the db `mod` to be public. They should only be accessible through our `Backend` struct

2024-01-17 10:53 UTC, tdelabro commented on crates/client/db/src/lib.rs
> +pub mod messaging_db;
I would reexport `LastSyncedEventBlock` struct in `lib.rs`

2024-01-18 09:25 UTC, tdelabro approved these changes

2024-01-18 09:25 UTC, tdelabro commented on crates/client/db/src/messaging_db.rs
> +    pub fn last_synced_l1_block_with_event(&self) -> Result<LastSyncedEventBlock, DbError> {
`last_synced_l1_block_and_event`

2024-01-19 11:00 UTC, merged