feat: :white_check_mark: Adding test for getNonce RPC Call if Contrac…
keep-starknet-strange/madara pull request #1374
Opened 2024-01-16 15:11 UTC by Tbelleng

# Description

Solve issue : #1373 

Adding a test for getNonce RPC call in case the contract doesnt exist/ is invalid. 
I Also changed the "nonce" function in order to return None instead of a Nonce::Default().
The precedent version of Madara, when a invalid contract was tested, didnt produce any error and was
just return a default Nonce, equal to 0, which is a valid nonce on Starknet. 
By this return, the ContractError was never triggered, resulting with a valid nonce return.

# Pull Request type

- Bugfix
- Testing

## What is the new behavior?

By changing the nonce return in case of error and adding a test in case of an invalid contract,
its return the right error.

## Does this introduce a breaking change?

No

## Other information

2024-01-16 17:32 UTC, Tbelleng commented
Hello @tdelabro 
Its seems that turning nonce to None instead of default (which turn nonce into a 0 which is a valid nonce) invalid 4 tests into madara : 
- fail_execution_step_with_no_storage_change
- fail_validation_step
- fails_already_declared
- works_with_storage_change

So 3 of these test fail earlier than expected by madara because of the nonce = None.
Is it a normal behavior or those tests need to be fixed ?

2024-01-17 10:10 UTC, tdelabro commented
> Hello @tdelabro Its seems that turning nonce to None instead of default (which turn nonce into a 0 which is a valid nonce) invalid 4 tests into madara :
> 
>     * fail_execution_step_with_no_storage_change
> 
>     * fail_validation_step
> 
>     * fails_already_declared
> 
>     * works_with_storage_change
> 
> 
> So 3 of these test fail earlier than expected by madara because of the nonce = None. Is it a normal behavior or those tests need to be fixed ?

I'm we will need you to fix those tests. And I'm unsure why they fail. But I will be happy to help you if you need

2024-01-17 10:32 UTC, Tbelleng commented
thanks @tdelabro !
By doing differently i fixed those tests but i got a failure at this one : works_with_deploy_account_txn
My implmentation trigger an error when the "get_nonce" function is used.
I guess its might come from the fact that within this test, madara use to set-up a valid nonce at 0, because the contract doesnt have one.
But with the new implementation, if a contract doesnt have any nonce (not even 0), its trigger the ContractNotFound error (because a contract with no nonce cant exist), so the test that was working before, fail with the new implementation.

2024-01-17 12:57 UTC, Tbelleng commented
Tests passed ✅ The one that fail now is : work_ok_non_used_contract_address because this test must fail and its fail with the new implementation, but for an unknow reason the test, in the current madara version, is considered as valid.
My suggestion is to remove this test, or to modify it to expect a fail instead of an Ok().

2024-01-17 13:14 UTC, tdelabro requested changes

2024-01-17 13:14 UTC, tdelabro commented on starknet-rpc-test/get_block_with_txs.rs
> +        // account_deploy_txn.address()).await?;
Remove rather than comment

2024-01-17 14:12 UTC, tdelabro approved these changes

2024-01-17 14:13 UTC, merged