Add transaction_from_json helper function and refactor StarkNet pallet tests
keep-starknet-strange/madara pull request #143
Opened 2023-04-03 12:59 UTC by Matth26

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

While writing tests for the starknet pallet, new transactions have to be manually created by using its constructor Transaction::new. This is very cumbersome and affects tests' readability overall.

Issue Number: #111 

# What is the new behavior?

- A new helper function, `transaction_from_json`, has been added. This function allows users to create Transaction objects directly from json files. 
- json transaction files are now stored in a dedicated `/resources/transactions` subfolder. 

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

All elements of the Transaction come from the json except for the `pub contract_class: Option<ContractClassWrapper>` field. 

The existing tests use a file from the blockifier crate, imported with the `include_bytes!` macro. So I opted to exclude it from the json and incorporate it as a function argument instead:

```Rust
pub fn transaction_from_json(json_str: &str, contract_content: &'static [u8])
```

If `contract_content` is set to `&[]`, the `contract_class` field will be set to `None`. Otherwise, we create the `ContractClassWrapper` from the `contract_content`.

2023-04-03 17:32 UTC, EvolveArt requested changes
Thanks for this! A few changes I'd like to see tho : 
- You could put the code from `transaction_from_json` in the `starknet_serde` primitive module.
- No need to rewrite all the tests, just modifying the existing ones to use the helper function will be fine
- I would like to see tests only on serialization/derserialization. Edge cases where it fails should be covered there.
- Finally would be great to have more explicit names about what the transactions actually do instead of referring to test names

2023-04-06 12:28 UTC, abdelhamidbakhta requested changes
left few comments

2023-04-06 12:28 UTC, abdelhamidbakhta commented on crates/primitives/starknet/src/starknet_serde/mod.rs
> +fn remove_prefix(input: &str) -> &str {
please add rust doc

2023-04-06 16:37 UTC, EvolveArt approved these changes
lgtm

2023-04-10 08:15 UTC, abdelhamidbakhta approved these changes

2023-04-10 08:16 UTC, merged