Add tests for estimate_message_fee RPC Call
keep-starknet-strange/madara pull request #1431
Opened 2024-02-02 14:11 UTC by Tbelleng

Add some tests for estimate_message_fee RPC call 

# Pull Request type

- Testing

## What is the current behavior?

Resolves: #1412

## What is the new behavior?

## Does this introduce a breaking change?

No

## Other information

2024-02-07 13:39 UTC, Tbelleng commented
Do you guys know can i create a message L1->L2 in order to estimate it thanks to the rpc Call ? 
Im trying to do that in my last test and @tdelabro told me that i have to use the ```"test_l1_handler_store_under_caller_address"``` cairo function in order to do so. But as far as i know, all cairo function are executed by using an account (because to simulate tx you just have to do L2->L2). But concerning estimateMessageFee, the transaction that we have to estimate is a L1->L2 message (where L1 account is Starknet contract on ETH and L2 account is ETH contract on Starknet), so i guess i dont have to initialize any account right ?

2024-02-08 14:40 UTC, tdelabro requested changes

2024-02-08 14:40 UTC, tdelabro commented on starknet-rpc-test/estimate_message_fee.rs
> +use starknet_rpc_test::fixtures::{madara, ThreadSafeMadaraClient};
fmt, add a space there

2024-02-08 14:40 UTC, tdelabro commented on starknet-rpc-test/estimate_message_fee.rs
> +// async fn works_ok(madara: &ThreadSafeMadaraClient) -> Result<(), anyhow::Error> {
You need to uncomment this and do an estimate_message that works

2024-02-08 14:40 UTC, tdelabro commented on starknet-rpc-test/estimate_message_fee.rs
> +// async fn works_ok(madara: &ThreadSafeMadaraClient) -> Result<(), anyhow::Error> {
The todo later is only about the fact of actually executing the message afterward and compare it's cost with the estimation

2024-02-09 08:35 UTC, tdelabro requested changes

2024-02-09 08:35 UTC, tdelabro commented on starknet-rpc-test/estimate_message_fee.rs
> +    };
Bha la par contre il va failloir utiliser des valeurs qui fonctionnent.

La fonction que tu veux call c'est celle là:
```rust
@l1_handler
func test_l1_handler_store_under_caller_address{syscall_ptr: felt*}(from_address: felt, value: felt) {
    storage_write(address=from_address, value=value);
    return ();
}
```
dans  cairo-contracts/src/test_contracts/test.cairo

Donc là il faut que tu changes to entry_point_selector:
```shell
$ starkli selector test_l1_handler_store_under_caller_address
0x014093c40d95d0a3641c087f7d48d55160e1a58bc7c07b0d2323efeeb3087269
```

Et ton addresse:
```rust
pub const TEST_CONTRACT_ADDRESS: &str = "0x0000000000000000000000000000000000000000000000000000000000001111";
```
dans `starknet-rpc-test/src/constants.rs`

Sinon il appelle un entrypoint qui existe pas sur un contract qui existe pas.

2024-02-13 12:19 UTC, tdelabro approved these changes

2024-02-13 12:19 UTC, merged