add: from_address in l1 message calldata
keep-starknet-strange/madara pull request #1451
Opened 2024-02-17 10:32 UTC by anshalshukla

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2024-02-17 10:48 UTC, apoorvsadana approved these changes

2024-02-19 07:49 UTC, tdelabro requested changes

2024-02-19 07:49 UTC, tdelabro commented on crates/client/l1-messages/src/contract.rs
> +    let mut calldata: Vec<Felt252Wrapper> = vec![from_address];
you can preallocate the correct length there: event.payload.len() + 1

2024-02-19 07:49 UTC, tdelabro commented on crates/client/l1-messages/src/contract.rs
> +    let mut calldata: Vec<Felt252Wrapper> = vec![from_address];
and use https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect_into to populate the allocated vec

2024-02-19 16:39 UTC, tdelabro approved these changes

2024-02-19 16:40 UTC, merged