Verify tx version on execute
keep-starknet-strange/madara pull request #162
Opened 2023-04-05 10:23 UTC by zediogoviana

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

The current `execute` method doesn't check if the transaction version being passed is valid or not.
`Transaction.version` uses a `U256` as the type.

Issue Number: #127 

# What is the new behavior?

This PR adds a transaction version validation similar to what happens in the [blockifier](https://github.com/tdelabro/blockifier/blob/no_std-support/crates/blockifier/src/transaction/account_transaction.rs#L100).
It also replaces the usage of `U256` for the version type in the `Transaction` struct to be an `u8`, as specified in the issue.

Existing tests were updated, and new ones were added.

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

2023-04-05 10:29 UTC, zediogoviana commented
Hey @abdelhamidbakhta 👋 This should be ready to be reviewed

2023-04-05 10:55 UTC, abdelhamidbakhta requested changes
left some comments

2023-04-05 13:38 UTC, zediogoviana commented on crates/primitives/starknet/src/transaction/mod.rs
> +        let allowed_versions: vec::Vec<TransactionVersion> = match tx_type {
When you mention the allowed versions to be in storage, do you have an idea of how the "association" with tx type should happen? 
For example, in the blockifier, the Declare can be valid for v0 and v1. This issue mentions a similar thing `Should only accept transaction v1 except for declare`. 
Should it be a hashmap/dictionary/struct to map which versions are allowed for each `TxType`?

2023-04-05 14:09 UTC, abdelhamidbakhta commented on crates/primitives/starknet/src/transaction/mod.rs
> +        let allowed_versions: vec::Vec<TransactionVersion> = match tx_type {
good point, ok nevermind let's not put it in storage to avoid also an extra overhead in terms of performance 👍

2023-04-05 14:17 UTC, zediogoviana commented on crates/primitives/starknet/src/transaction/mod.rs
> +        let allowed_versions: vec::Vec<TransactionVersion> = match tx_type {
Ok, got it! Btw, are the version checks correct? I used the same as in the `blockifier`, but just checking if there should be any difference here.

2023-04-05 14:57 UTC, abdelhamidbakhta commented on crates/primitives/starknet/src/transaction/mod.rs
> +        let allowed_versions: vec::Vec<TransactionVersion> = match tx_type {
yes they are correct

2023-04-06 09:39 UTC, EvolveArt commented
hey @zediogoviana, could you add one test within `starknet/lib.rs` ? Just to make sure it fails correctly when given two non-consecutive nonces.

2023-04-06 09:45 UTC, zediogoviana commented
Hey @EvolveArt, I can do that, no problem. However, I'm not understanding how the nonce verification test impacts this PR. Just checking if you aren't referring to PR #129 instead.

2023-04-06 09:55 UTC, EvolveArt commented
> Hey @EvolveArt, I can do that, no problem. However, I'm not understanding how the nonce verification test impacts this PR. Just checking if you aren't referring to PR #129 instead.

Sorry I meant tx version you're right, got confused between PRs

2023-04-06 10:51 UTC, EvolveArt approved these changes
lgtm

2023-04-06 10:58 UTC, merged