Implement functions to calculate global root.
keep-starknet-strange/madara pull request #166
Opened 2023-04-05 22:16 UTC by ben2077

…e root, and global state root.

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

# Other information

2023-04-07 12:17 UTC, abdelhamidbakhta requested changes
left comments

2023-04-07 12:17 UTC, abdelhamidbakhta commented on crates/primitives/starknet/src/crypto/commitment/mod.rs
> +pub fn calculate_global_state_root<T: CryptoHasher>(contract_state_root: H256, classes_root: H256) -> H256 {
please add rust doc comments (arguments, returns)

2023-04-10 09:26 UTC, abdelhamidbakhta commented
hey @ben2077 what's the status of this PR ?

2023-04-14 10:07 UTC, LucasLvy commented
Do you need help for this ?

2023-04-20 06:32 UTC, closed without merging