feat: manual sealing ✨
keep-starknet-strange/madara pull request #220
Opened 2023-04-11 18:25 UTC by EvolveArt

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

- Implement the `sc-consensus-manual-sealing` pallet.
- Add a `--sealing` option to the `cli`
- Add a new `DevChainSpec` chain spec type

# Does this introduce a breaking change?

- [x] Yes
- [ ] No

# Other information

Highly inspired by the work done by [frontier](https://github.com/paritytech/frontier/blob/master/template/node/src/chain_spec.rs#L27)

2023-04-13 15:55 UTC, abdelhamidbakhta requested changes
left some comments

2023-04-13 15:55 UTC, abdelhamidbakhta commented on Cargo.toml
> +sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.40", default-features = false }
please add a comment saying this is for testing purpose for RPC endpoints and why we need this

2023-04-13 15:55 UTC, abdelhamidbakhta commented on crates/node/src/chain_spec.rs
> +    fn assimilate_storage(&self, storage: &mut Storage) -> Result<(), String> {
add rust doc

2023-04-13 15:55 UTC, abdelhamidbakhta commented on crates/node/src/chain_spec.rs
> +    fn assimilate_storage(&self, storage: &mut Storage) -> Result<(), String> {
also if you can ELI5 why it's needed it would be great

2023-04-13 15:55 UTC, abdelhamidbakhta commented on crates/node/src/rpc/mod.rs
> +    /// Manual seal command sink
what does command sink mean ?

2023-04-13 15:55 UTC, abdelhamidbakhta commented on crates/runtime/src/config.rs
> +parameter_types! {
explain what is this config used for

2023-04-13 15:55 UTC, abdelhamidbakhta commented on crates/runtime/src/pallets.rs
> +    fn on_timestamp_set(moment: T::Moment) {
rust doc

2023-04-13 16:07 UTC, EvolveArt commented on crates/node/src/rpc/mod.rs
> +    /// Manual seal command sink
un robinet de commandes a.k.a a stream

2023-04-14 09:34 UTC, abdelhamidbakhta approved these changes
lgtm

2023-04-14 09:34 UTC, merged