feat: RPC - starknet_syncing
keep-starknet-strange/madara pull request #257
Opened 2023-04-19 09:50 UTC by zediogoviana

RPC Endpoint that returns an object about the sync status, or false if the node is not syncing.

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Creating a new RPC Endpoint.

Issue Number: #205 

# What is the new behavior?

This new endpoint looks for `starting_block`, `current_block` and `highest_block`, provided by the `sync_service`. With each block, we get the corresponding Starknet block and return its numbers and hashes respectively.

If the node is not syncing, then it returns false.

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

2023-04-19 11:16 UTC, abdelhamidbakhta requested changes
left some comments. also integration tests are missing for the new RPC

2023-04-19 11:16 UTC, abdelhamidbakhta commented on crates/client/rpc/src/lib.rs
> +    pub fn new(
please add rust doc

2023-04-19 11:16 UTC, abdelhamidbakhta commented on crates/client/rpc/src/lib.rs
> +    async fn syncing(&self) -> RpcResult<Syncing> {
please add rust doc

2023-04-19 11:16 UTC, abdelhamidbakhta commented on crates/client/rpc/src/lib.rs
> +    async fn syncing(&self) -> RpcResult<Syncing> {
please add comments in the function body to explain the steps

2023-04-19 11:16 UTC, abdelhamidbakhta commented on crates/client/rpc/src/madara_backend_client.rs
> +pub fn starknet_block_from_substrate_hash<B: BlockT, C, BE>(
please add rust doc

2023-04-20 20:21 UTC, EvolveArt commented
Thanks a lot for this @zediogoviana ! Would it be possible to add some integration tests in typescript as well ?

2023-04-21 13:37 UTC, zediogoviana commented
Yeah @EvolveArt , I'll do it. This week I've been attending ElixirConf in Lisbon, so time has been short to pick this up.

2023-05-03 11:03 UTC, zediogoviana commented
After talking with @EvolveArt, I’ve been reading about Zombienet and how it could help with the missing test for the syncing RPC endpoint (the situation where the endpoint returns `false`). I’ve also searched on [substrate's node options](https://docs.substrate.io/reference/command-line-tools/node-template/) to see if there is anything related to syncing that I can toggle, but nothing seems to be what I want… I also found [this question](https://substrate.stackexchange.com/questions/6472/how-to-perform-manual-sync) that’s pretty much what I want, but the answer says the guy can’t do it, and he should try `--in-peers` and `--out-peers` to `0` but that’s already the case we have in the current test setup.

This way, @EvolveArt suggested moving ahead and opening an issue with these findings. So if everyone agrees, and when this gets merged, I'll do just that.

2023-05-03 13:00 UTC, EvolveArt submitted a review, later dismissed
left few comments

2023-05-03 13:00 UTC, EvolveArt commented on crates/node/src/rpc/starknet.rs
> +    pub sync_service: Arc<SyncingService<B>>,
rustdoc

2023-05-03 13:00 UTC, EvolveArt commented on crates/node/src/rpc/starknet.rs
> +    pub starting_block: <<B>::Header as HeaderT>::Number,
rustdoc

2023-05-03 13:00 UTC, EvolveArt commented on tests/tests/test-rpc/test-starknet-rpc.ts
> +    expect(status["sync_status"]["starting_block_hash"]).to.contain("0xaf");
explain why these values in comments

2023-05-04 09:02 UTC, abdelhamidbakhta approved these changes
lgtm

2023-05-04 09:05 UTC, abdelhamidbakhta approved these changes
lgtm

2023-05-04 09:07 UTC, merged