feat: RPC - add `starknet_getClassHashAt`
keep-starknet-strange/madara pull request #276
Opened 2023-04-20 07:40 UTC by ftupas

Implement `starknet_getClassHashAt` RPC that gets the contract class hash in the given block for the contract deployed at the given address

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #196 

# What is the new behavior?
- Add `getClassHashAt` to RPC client
- Test `getClassHashAt` RPC method
- Fix #196 

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/35031356/233294272-abdfee81-6a0d-4690-92da-dc609ff17936.png">

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

2023-04-20 22:06 UTC, EvolveArt requested changes
left few comments, please improve integration tests (add more cases and test return values)

2023-04-20 22:06 UTC, EvolveArt commented on crates/client/rpc/src/lib.rs
> +        Ok(StarkFelt::new(class_hash).unwrap().to_string())
no `unwrap` please

2023-04-20 22:06 UTC, EvolveArt commented on crates/client/storage/src/overrides/mod.rs
> +    fn contract_class_hash_by_address(
comment + formatting

2023-04-21 07:21 UTC, ftupas commented
> left few comments, please improve integration tests (add more cases and test return values)

Thanks for the review @EvolveArt , will update accordingly ✌️

2023-04-27 09:35 UTC, ftupas commented on crates/client/storage/src/overrides/mod.rs
> +    fn contract_class_hash_by_address(
Updated with comment and formatting 👍

2023-04-27 09:35 UTC, ftupas commented on crates/client/rpc-core/src/lib.rs
> +pub type Address = String;
Decided to use the existing `ContractAddress` instead

2023-04-27 09:35 UTC, ftupas commented on crates/client/rpc/src/lib.rs
> +        Ok(StarkFelt::new(class_hash).unwrap().to_string())
Update this one 👍

2023-05-01 14:39 UTC, abdelhamidbakhta commented
hey @ftupas what is the status of this PR ?

2023-05-01 15:02 UTC, ftupas commented
> hey @ftupas what is the status of this PR ?

Hi @abdelhamidbakhta, it's up for review normally I've resolved the conflicts 🤙 I've also improved the integration test by adding more test cases

2023-05-01 15:03 UTC, abdelhamidbakhta commented
> > hey @ftupas what is the status of this PR ?
> 
> Hi @abdelhamidbakhta, it's up for review normally I've resolved the conflicts 🤙 I've also improved the integration test by adding more test cases

awesome thanks for the prompt reply. I will leave @EvolveArt continue the review then

2023-05-04 14:04 UTC, EvolveArt approved these changes
lgtm

2023-05-04 14:50 UTC, merged