Feat/validate
keep-starknet-strange/madara pull request #312
Opened 2023-04-30 13:29 UTC by greged93

Add the validation entrypoint call in the execution pipeline.

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Currently, the `__validate__` entrypoint is not called on the account contract executing the transaction.

Issue Number: #227 

# What is the new behavior?

- Add `validate_tx` in order to call the correct validation entrypoint on the sender account
- Add general testing with various validation patterns (Argent, Braavos, Openzeppelin)
- Add edge cases to the test suite

# Does this introduce a breaking change?

- [x] Yes
- [ ] No

2023-05-06 14:43 UTC, LucasLvy commented on crates/pallets/starknet/src/tests/declare_tx.rs
> +        assert_ok!(Starknet::declare(none_origin, transaction));
also check that the class is indeed declared and the declared class = the one that you declared. Something like that
```rs
assert_eq!(Starknet::contract_class_from_class_hash(erc20_class_hash), erc20_class)
```

2023-05-06 15:05 UTC, LucasLvy requested changes
Also compile the contracts with 0.10.3 plz

2023-05-06 15:05 UTC, LucasLvy commented on crates/primitives/starknet/Cargo.toml
> +itertools = { workspace = true }
Why is it needed ?

2023-05-06 15:05 UTC, LucasLvy commented on Cargo.toml
> +itertools = { version = "0.10.3", default-features = false }
why do you need it ?

2023-05-08 09:07 UTC, greged93 commented on crates/primitives/starknet/src/transaction/mod.rs
> +                    self.try_into().map_err(TransactionExecutionErrorWrapper::StarknetApi)?;
This is the type of error returned by the `try_into`, see [here](https://github.com/keep-starknet-strange/madara/blob/main/crates/primitives/starknet/src/transaction/mod.rs#L178).

2023-05-08 09:09 UTC, greged93 commented on crates/primitives/starknet/src/transaction/mod.rs
> +                self.validate_tx(state, execution_resources, &block_context, &account_context, &tx_type)?;
In the case of account deployment, validation should come after execution, see [here](https://github.com/tdelabro/blockifier/blob/main/crates/blockifier/src/transaction/account_transaction.rs#L294).

2023-05-11 06:44 UTC, abdelhamidbakhta approved these changes
lgtm

2023-05-11 06:44 UTC, merged