bug: docker instance not able to run npm scripts fix
keep-starknet-strange/madara pull request #410
Opened 2023-05-19 04:01 UTC by dbejarano820

The docker instance currently doesn't have the capability of running npm scripts since Node.js and npm aren't installed. This PR fixes that by adding a line to install them and removing a line which erases the bin directories.

# Pull Request type
Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?
Docker instance isn't able to run npm scripts

Resolves: #285 

## What is the new behavior?
Added missing step to install Node.js and npm in the container, which are required to run `npm run test-seq`.

I'm 100% sure about this other change but I eliminated the lines which removes /usr/bin and /usr/sbin since it's affecting the ability to run Node.js and npm inside the container.

Another alternative could be creating a separate container to run the npm scripts, this way we could avoid removing the line. Let me know!

## Does this introduce a breaking change?
No

## Other information

2023-05-19 07:17 UTC, dbejarano820 commented
I will create a separate Dev Dockerfile instead of adding node dependencies to the production image

2023-05-19 07:26 UTC, abdelhamidbakhta commented
> I will create a separate Dev Dockerfile instead of adding node dependencies to the production image

Awesome, thanks

2023-05-19 07:27 UTC, abdelhamidbakhta requested changes
Waiting for the separate docker file, as discussed.

2023-05-20 23:04 UTC, abdelhamidbakhta approved these changes
Lgtm

2023-05-20 23:04 UTC, abdelhamidbakhta approved these changes
Lgtm

2023-05-20 23:04 UTC, merged