fix: to_rpc_contract_class ✨
keep-starknet-strange/madara pull request #485
Opened 2023-05-29 09:13 UTC by EvolveArt

## What is the current behavior?

Resolves: #363 

## What is the new behavior?

Fixes `to_rpc_contract_class`, converts to a legacy contract class.

## Does this introduce a breaking change?

No

## Other information

2023-05-29 09:33 UTC, EvolveArt commented
We need to wait for this to be fixed https://github.com/lambdaclass/cairo-rs/issues/1183

2023-06-05 13:50 UTC, LucasLvy requested changes

2023-06-05 13:50 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +    Ok(LegacyEntryPointsByType { constructor, external, l1_handler })
remove unwraps

2023-06-05 13:50 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +fn _to_legacy_entry_points_by_type(
```suggestion
fn to_legacy_entry_points_by_type(
```

2023-06-05 13:50 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +fn _get_entrypoint_value(entries: Vec<LegacyContractEntryPoint>) -> BoundedVec<EntryPointWrapper, MaxEntryPoints> {
```suggestion
fn get_entrypoint_value(entries: Vec<LegacyContractEntryPoint>) -> BoundedVec<EntryPointWrapper, MaxEntryPoints> {
```

2023-06-05 13:50 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
>  fn _to_btree_map_entrypoints(
```suggestion
fn to_btree_map_entrypoints(
```

2023-06-05 15:55 UTC, LucasLvy requested changes

2023-06-05 15:55 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +fn to_btree_map_entrypoints(
impl from trait ?

2023-06-05 15:55 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +fn to_legacy_entry_points_by_type(
impl from trait ?

2023-06-05 16:03 UTC, LucasLvy requested changes

2023-06-05 16:03 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +/// Converts a broadcasted deploy account transaction to a deploy account transaction
from trait ?

2023-06-05 16:03 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +/// Converts a broadcasted declare transaction to a declare transaction
from trait ?

2023-06-06 07:55 UTC, LucasLvy approved these changes

2023-06-06 07:55 UTC, merged