add pool futures to pending transactions
keep-starknet-strange/madara pull request #622
Opened 2023-06-13 09:47 UTC by greged93

Update the `pendingTransactions` endpoint in order to include transactions that are currently in the `future` pool.

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?
The `pendingTransactions` endpoint will only return the transactions that have been placed in the `ready` queue, missing the transactions from the `future` queue (see [docs](https://docs.substrate.io/learn/transaction-lifecycle/#validating-and-queuing-transactions)).

Resolves: #NA

## What is the new behavior?
The rpc endpoint returns all transactions from the pool, in `ready` or `future` queue.

- Added the pool graph instance to the Starknet RPC structure in order to gain access to the `future` transaction queue

## Does this introduce a breaking change?
No

2023-06-13 09:49 UTC, greged93 commented
PR is missing tests to prove that extrinsics in the `future` queue are indeed returned. I was not able to find how I could submit a transaction which includes a `require` tag, which would allow me to test the correct behaviour.

2023-06-13 20:07 UTC, EvolveArt requested changes
left a few comments

2023-06-13 20:07 UTC, EvolveArt commented on tests/tests/test-rpc/test-starknet-rpc.ts
> +
add an expect for pendings value ?

2023-06-14 08:51 UTC, greged93 commented on crates/node/src/service.rs
> +        let graph = transaction_pool.pool().clone();
The way I understand it: we use the transaction pool for pool and in the RPC, we submit extrinsics to it via the trait `TransactionPool<Block = B>`. The graph is then one level lower and represents the dependency graph that exists between all the transactions in the pool. 
I think the naming used in substrate might be a little confusing, `transaction_pool.pool()` returns a `graph::Pool` instance hence representing this graph.

2023-06-14 08:53 UTC, greged93 commented on crates/client/rpc/src/lib.rs
> +            self.graph.validated_pool().futures().into_iter().map(|(_hash, extrinsic)| extrinsic).collect();
`futures()` actually returns a `Vec<(hash, extrinsic)>`, but we are only interested in the extrinsic.

2023-06-14 14:16 UTC, greged93 commented on crates/node/src/service.rs
> +        let graph = transaction_pool.pool().clone();
will make an issue for this!

2023-06-14 14:54 UTC, EvolveArt commented on crates/pallets/starknet/src/lib.rs
> +            |_err| {
remove the `_`

2023-06-14 15:02 UTC, EvolveArt approved these changes
lgtm

2023-06-14 15:29 UTC, merged