dev: Use taplo to format TOML files of the project
keep-starknet-strange/madara pull request #642
Opened 2023-06-14 15:01 UTC by ApereLieZ

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)

## What is the current behavior?

Resolves: #607

## What is the new behavior?

- Add instructions on how to run taplo locally
- Add a formatting rules file for universal formatting
- Add a workflow in the CI to check the formal of TOML files and fail if not valid
- add husky hooks with TOML file validation (need to run hooks once)

## Does this introduce a breaking change?

Yes
You must check the TOML files before pushing, otherwise ci/cd will fail.
To prevent this behavior, enable husky hooks (in root folder type)
 
```bash
npm install
```

2023-06-15 13:49 UTC, EvolveArt requested changes
As said in madara channel :
> couldn't we just use the taplo rust crate. Not a huge fan of having to add npm dependencies at the root of the project..

We should rather use [cargo-husky](https://github.com/rhysd/cargo-husky) there imo

2023-06-15 22:14 UTC, EvolveArt commented on .github/workflows/test.yml
> +  toml-lint:
add spacing here

2023-06-15 22:29 UTC, EvolveArt commented
@ApereLieZ why does it still use `npx @taplo/cli` in the CI ? I don't get why we cannot just use the [taplo](https://crates.io/crates/taplo/0.12.0) crate ?

2023-06-16 07:59 UTC, ApereLieZ commented
> @ApereLieZ why does it still use `npx @taplo/cli` in the CI ? I don't get why we cannot just use the [taplo](https://crates.io/crates/taplo/0.12.0) crate ?

From my measurements in terms of runtime, using npx is noticeably faster than using crate

2023-06-19 08:46 UTC, EvolveArt commented
> > @ApereLieZ why does it still use `npx @taplo/cli` in the CI ? I don't get why we cannot just use the [taplo](https://crates.io/crates/taplo/0.12.0) crate ?
> 
> @EvolveArt From my measurements in terms of runtime, using npx is noticeably faster than using crate

But then no need to `cargo add taplo-cli` in this case ?

2023-06-19 08:46 UTC, EvolveArt approved these changes
lgtm

2023-06-19 13:41 UTC, ApereLieZ commented
@EvolveArt 
Done

2023-06-19 14:48 UTC, merged