feat: store sierra class in runtime when using declare v2
keep-starknet-strange/madara pull request #817
Opened 2023-07-04 22:24 UTC by tdelabro

# Current behaviour

using declare_v2, the sierra program is not used

## What is the new behavior?

- the sierra program is now stored in the runtime
- it is returned when calling the get_class rpc method

## Does this introduce a breaking change?

No

2023-07-05 09:29 UTC, LucasLvy requested changes

2023-07-05 09:29 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/utils.rs
> +    use alloc::vec::Vec;
In feature std ?

2023-07-05 09:37 UTC, tdelabro commented on crates/primitives/starknet/src/transaction/utils.rs
> +    use alloc::vec::Vec;
Oh yes. Weird one

2023-07-06 20:17 UTC, EvolveArt requested changes
left few comments

2023-07-06 20:17 UTC, EvolveArt commented on crates/client/rpc/src/lib.rs
> +                StarknetRpcApiError::ContractNotFound.into()
`into` needed ?

2023-07-06 20:17 UTC, EvolveArt commented on crates/pallets/starknet/src/lib.rs
> +            if let Some(sierra_class) = sierra_program {
so it can be none ? what happens in this case ? means its casm directly right ?

2023-07-06 20:17 UTC, EvolveArt commented on crates/primitives/starknet/Cargo.toml
> +starknet-core = { workspace = true }
`default-features = false` no ?

2023-07-06 20:17 UTC, EvolveArt commented on crates/primitives/starknet/src/execution/sierra_contract_class.rs
> +// O(0) type conversion conversion
O(0) ?

2023-07-06 20:17 UTC, EvolveArt commented on crates/primitives/starknet/src/transaction/types.rs
> +impl TryFrom<(DeployAccountTransaction, Felt252Wrapper)> for Transaction {
how idiomatic is that kind of pattern ? I find it quite misleading and not sure that rustdoc would make it easy to understand

2023-08-18 08:36 UTC, closed without merging