Refactoring Transaction type to enum
keep-starknet-strange/madara pull request #826
Opened 2023-07-05 14:43 UTC by MavericksFive

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Refactoring 

## What is the current behavior?

Resolves: #457 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2023-07-12 09:28 UTC, abdelhamidbakhta commented
hey @MavericksFive any ETA  for this PR ?

2023-07-12 10:07 UTC, MavericksFive commented
> hey @MavericksFive any ETA for this PR ?

Hey @abdelhamidbakhta, it should be less than one week! We should raise an Issue as well on L1HandlerTransaction type as for now I have implemented Transaction without it... (Because L1HandlerTransaction is causing some issues)

2023-07-12 10:33 UTC, abdelhamidbakhta commented
> > hey @MavericksFive any ETA for this PR ?
> 
> Hey @abdelhamidbakhta, it should be less than one week! We should raise an Issue as well on L1HandlerTransaction type as for now I have implemented Transaction without it... (Because L1HandlerTransaction is causing some issues)

got it, can you create the issue ?

2023-07-24 16:03 UTC, MavericksFive commented
> What's the state of this ?

Hey, I have opened some issues to finish implementing the transaction to enum!

2023-07-24 16:41 UTC, LucasLvy commented
what's up with all the commented code ?

2023-07-24 17:17 UTC, MavericksFive commented
> what's up with all the commented code ?

My bad... I forgot to uncomment some tests

2023-07-31 07:53 UTC, LucasLvy requested changes
You need to rebase

2023-07-31 07:53 UTC, LucasLvy commented on crates/client/rpc-core/src/tests.rs
> +    let output_result: Result<DeclareTransaction, _> = to_declare_transaction(input, chain_id);
This feels like an old version of madara we now use the `From` `TryFrom` trait to be able to directly use `into` or `try_into`. If we don't do that for this type then please add it.

2023-07-31 07:53 UTC, LucasLvy commented on crates/client/rpc-core/src/utils.rs
> +use std::convert::From;
no need to import this

2023-07-31 07:53 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/types.rs
> +    pub transaction_hash: Felt252Wrapper,
don't add this field in the struct otherwise anyone can set anything he likes when sending the tx using the polkadot sdk

2023-07-31 07:53 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/types.rs
> +    #[error("Wrong transaction type (Invoke) from the object of type [Transaction]")]
Error message is not that clear

2023-07-31 07:53 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/types.rs
> +        ) -> Result<InvokeTransaction, BroadcastedTransactionConversionErrorWrapper> {
`impl TryFrom<BroadcastedInvokeTransaction> for InvokeTransaction {`

2023-08-11 08:15 UTC, closed without merging

2023-08-16 10:01 UTC, tdelabro commented
Hey @MavericksFive,
I closed the PR cause this is going to be solved by another PR addressing another issue but requiring the same kind of changes.
I'm sorry this lack of coordination led to a misused of your time :(