feat: nonce validation config
keep-starknet-strange/madara pull request #869
Opened 2023-07-13 15:10 UTC by greged93

Add nonce validation configuration.
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Testing

## What is the current behavior?
Nonce validation is always applied.

Resolves: #846 

## What is the new behavior?
Nonce validation is set by default but can be deactivated.

- Add nonce validation enabling in the config.
- Test nonce validation config.

## Does this introduce a breaking change?
Yes

2023-07-13 15:12 UTC, greged93 commented
Nonce ordering is still kept in the `validate_unsigned` call. Can be skipped if nonce validation is disabled but for me seems normal to keep it.

2023-07-16 13:19 UTC, EvolveArt requested changes
left few comments, ideally lets merge #868 first cause it comes up with a nice refractor of `MockRuntime` configs

2023-07-16 13:19 UTC, EvolveArt commented on crates/pallets/starknet/src/tests/constants.rs
> +pub const SALT: &str = "0x03b37cbe4e9eac89d54c5f7cc6329a63a63e8c8db2bf936f981041e086752463";
add comment

2023-07-16 13:19 UTC, EvolveArt commented on crates/pallets/starknet/src/tests/mod.rs
> +pub fn get_declare_dummy(account_type: AccountType) -> DeclareTransaction {
rust doc

2023-07-16 13:19 UTC, EvolveArt commented on crates/pallets/starknet/src/tests/mod.rs
> +pub fn get_deploy_account_dummy(salt: &str, account_type: AccountType) -> DeployAccountTransaction {
rustdoc

2023-07-16 13:19 UTC, EvolveArt commented on crates/pallets/starknet/src/tests/mod.rs
> +pub fn set_infinite_tokens<T: Config>(address: Felt252Wrapper) {
rustdoc

2023-07-16 13:19 UTC, EvolveArt commented on crates/pallets/starknet/src/tests/mod.rs
> +pub fn get_deploy_account_dummy(salt: &str, account_type: AccountType) -> DeployAccountTransaction {
why not salt as `Felt252Wrapper` ?

2023-07-19 12:21 UTC, EvolveArt requested changes
lgtm

2023-07-19 12:21 UTC, EvolveArt commented on crates/runtime/src/pallets.rs
> +    type EnableNonceValidation = ConstBool<true>;
miss the feature flags no?

2023-07-24 15:10 UTC, LucasLvy requested changes

2023-07-24 15:10 UTC, LucasLvy commented on crates/pallets/starknet/src/lib.rs
> +        /// It has been requested by certain apps to allow for nonce validation to be disabled
Remove this comment

2023-07-24 15:10 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/mod.rs
> +                Self::handle_nonce(state, disable_nonce_validation, &account_context, self.is_query)?;
Don't call that function if we don't validate the nonce

2023-07-24 15:10 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/mod.rs
> +                Self::handle_nonce(state, disable_nonce_validation, &account_context, self.is_query)?;
same here

2023-07-24 15:10 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/mod.rs
> +                Self::handle_nonce(state, disable_nonce_validation, &account_context, self.is_query)?;
same

2023-07-24 15:10 UTC, LucasLvy commented on crates/primitives/starknet/src/transaction/mod.rs
> +        disable_nonce_validation: bool,
no need for that then

2023-07-27 14:19 UTC, LucasLvy requested changes

2023-07-27 14:19 UTC, LucasLvy commented on crates/pallets/starknet/src/lib.rs
> +                false,
think you can set it to true as we don't use the nonce for those transactions

2023-07-27 14:19 UTC, LucasLvy commented on crates/pallets/starknet/src/lib.rs
> +            let disable_nonce_validation = T::DisableNonceValidation::get();
don't use an intermediate variable

2023-07-28 09:21 UTC, abdelhamidbakhta approved these changes
lgtm

2023-07-28 09:21 UTC, merged