translate madara article to russian
keep-starknet-strange/madara pull request #936
Opened 2023-07-30 14:40 UTC by gylman

- Feature
- Translation

Resolves: #929

2023-08-04 17:29 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +- Ее реализация дает множество преимуществ, таких как масштабируемая
Его (секвенсора)

2023-08-04 17:30 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +  конфиденциальности на чейне, оптимизированное взаимодействие между различными
лучше "в чейне"

2023-08-04 17:31 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +  чейнами и надежное исполнение.
лучше подойдет "отказоусточивое исполнение" или "отказоустойчивая работа"

2023-08-04 17:32 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +- Madara прокладывает путь в области разработки dApp, предлагая экономически
dApp -> децентрализованных приложений

2023-08-04 17:32 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +  эффективные, масштабируемые и настраиваемые решения в сфере блокчейна.
можно просто "блокчейн решения"

2023-08-04 17:39 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +которые предоставляют разработчикам гибкость в настройке отдельных аспектов
Здесь много тавтологии и неоднозначности:

Аппчейны — это блокчейны, которые предоставляют разработчикам гибкость в настройке отдельных аспектов в соответствии с потребностями их приложений, например, в выборе альтернативной хэш-функции или кастомизации алгоритма консенсуса.
 

Здесь лучше "предоставляющие" иначе как-будто речь про приложения
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
чейнов в соответствии с потребностями их приложений, например, выбор другой
хэш-функции или настройка алгоритма консенсуса.

2023-08-04 17:42 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +хэш-функции или настройка алгоритма консенсуса. Но самое главное? Аппчейны
Но самое главное — аппчейны наследуют безопаснось базовых уровней (L1 или L2) предоставляя разработчикам лучшее из обоих миров.

2023-08-04 17:43 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +молниеносную производительность. Секвенсоры - это объекты, отвечающие за
"сущности" — чуть более точный перевод

2023-08-04 17:45 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +выполнение транзакций и их группировку в батчи. Выступая в роли шлюза для
Т.к. термин не определен, можно как-нибудь так: "их группировку в пакеты (батчи)"

2023-08-04 17:46 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +запуска вашего собственного аппчейна Starknet, Madara открывает невиданные ранее
лучше убрать одно из упоминаний Starknet, чтобы не было тавтологии

2023-08-04 17:57 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +Прежде чем перейти к рассмотрению интересных возможностей Madara по созданию
Прежде чем перейти к рассмотрению интересных возможностей Madara важно ответить на вопрос, почему разработчики вдруг решат создавать L3 аппчейны на базе Starknet, а не использовать непосредственно решение [Starknet Validity Rollups](https://starkware.co/resource/scaling-ethereum-navigating-the-blockchain-trilemma/#:~:text=top%20of%20them.-,Validity%20Rollups,-Validity%20rollups%2C%20also). Можно предположить что и самой сети Starknet достаточно для большинства сценариев.

2023-08-04 17:58 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +Madara, разработанная командой StarkWare Exploration Team, также известной как
Можно опустить "Team"

2023-08-04 17:58 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +создана для реализации концепции
создан (секвенсор)

2023-08-04 18:00 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +создать аппчейн Starknet или L3 вместо того, чтобы напрямую полагаться на
создать L2 или L3 аппчейн (можно опустить здесь Starknet чтобы опять же убрать тавтологию)

2023-08-04 18:10 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +потенциально достигающего 1 000 000 раз. На пропускную способность не влияет
Запущенное в отдельном блокчейне приложение не конкурирует за ресурсы, поэтому внешняя активность никак не влияет на его пропускную способность. Это обеспечивает стабильно плавный пользовательский опыт.

2023-08-04 18:11 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +  чейнами и надежное исполнение.
сетями или блокчейнами

2023-08-04 18:11 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +чейнов в соответствии с потребностями их приложений, например, выбор другой
можно опустить "чейнов"

2023-08-04 18:12 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +В чейнах общего назначения, таких как Starknet и Ethereum, существует множество
В сетях

2023-08-04 18:17 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +индивидуальные решения. Не нравится функция VM Cairo? Устраните ее в своем
Лучше "какая-то функция"
Устраните -> Отключите

2023-08-04 18:19 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +авторизации любых желаемых подсказок кода. Это позволяет аппчейнам
Тут не понятно что имел в виду автор под "authorize any desired code hints" :)

2023-08-04 18:26 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +разблокировать множество вариантов использования, например, возможность
Это откроет дорогу (так как аппчейны предоставят) для множества сценариев использования, например применения on-chain KYC без утечки личной информации.

2023-08-04 20:58 UTC, gylman commented on docs/article/ru/madara beast article.md
> +  конфиденциальности на чейне, оптимизированное взаимодействие между различными
как насчет "ончейн конфиденциальности"

2023-08-04 20:59 UTC, gylman commented on docs/article/ru/madara beast article.md
> +- Madara прокладывает путь в области разработки dApp, предлагая экономически
Перевод этого слова не сложен, только стоит ли его переводить?

2023-08-05 09:41 UTC, gylman commented on docs/article/ru/madara beast article.md
> +индивидуальные решения. Не нравится функция VM Cairo? Устраните ее в своем
Можно же ведь полностью удалить какую либо функцию, в таком случае "Отключите" будет неправильно. Или удалять не позволяется?

2023-08-05 11:29 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +  конфиденциальности на чейне, оптимизированное взаимодействие между различными
можно "конфиденциальности транзакций" чтобы совсем понятно :)

2023-08-05 11:30 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +- Madara прокладывает путь в области разработки dApp, предлагая экономически
В целом согласен, просто кажется что там где переводится лучше переводить, англоязычных терминов и так достаточно

2023-08-05 11:34 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +индивидуальные решения. Не нравится функция VM Cairo? Устраните ее в своем
В целом можно, если переключить на свой форк сairo :)

2023-08-05 17:27 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +1. **Выполнение:** Слой выполнения определяет выполнение блоков и генерацию
**Исполнение:** Слой исполнения определяет то как выполняются блоки и генерируются обновления состояния. (убрал тавтологию + разности состояний это прямо совсем калька с английского)

2023-08-05 17:28 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   двумя контейнерами исполнения:
"двумя библиотеками" будет лучше, crate это все-таки не контейнер

(кстати мадара сейчас только blockifier поддерживает :D)

2023-08-05 17:29 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   Независимо от выбранного контейнера, в основе фреймворка используется VM
Независимо от выбранной библиотеки, в основе фреймворка используется виртуальная машина Cairo (либо Cairo VM, не VM Cairo)

2023-08-05 17:33 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   возможность продемонстрировать правильное выполнение вычислений.
более точно "продемонстрировать что вычисления произведены корректно"

2023-08-05 18:01 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   реконструировано только путем изучения его расчетного слоя. За счет более
тут имеется в виду что достаточно только settlement слоя чтобы восстановить стейт. Можно так:

"Как и для любого validity роллапа, для восстановления состояния Madara аппчейна достаточно данных из расчетного слоя".

2023-08-05 18:03 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   частых расчетов на Starknet L2 аппчейн L3 может быстрее достичь жесткой
Я бы взял в кавычки "жесткой"

2023-08-05 18:03 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   надежную мягкую финальность. Таким образом, расчеты улучшаются по обоим
"Мягкую" тоже лучше в кавычки кмк

2023-08-05 18:04 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   можно изменить в соответствии с потребностями приложения - будь то простые
изменить -> изменять

2023-08-05 18:06 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   FCFS, PGA или более сложные схемы, такие как Narwhall и Bullshark. Некоторые
Можно расшифровать в скобках (First-come-first-served), (Priority-gas-auction)

2023-08-05 18:07 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   справедливого упорядочивания и снижения влияния MEV.
тоже можно расшифровать

2023-08-05 18:08 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   [Snapshot X ](https://twitter.com/SnapshotLabs)предлагает полностью ончейн
пробел попал в ссылку

2023-08-05 18:10 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   изучаются альтернативные механизмы управления, такие как нативная палетка
палетка :DDD

Можно "нативный модуль управления из фреймворка Substrate"

2023-08-05 18:27 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +## Ввод: Madara
В оригинале похоже отсылка к биографии аниме персонажа :) https://naruto.fandom.com/wiki/Madara_Uchiha

Можно "Восхождение Madara"

2023-08-05 18:30 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +В Madara VM Cairo расширяется за счет использования фреймворка Substrate и
В Madara виртуальная машина Cairo (либо Cairo VM) обогащается за счет использования блокчейн фреймворка Substrate.

Дальше если честно какое-то бессмысленное предложение (в оригинале тоже), я предлагаю убрать.

2023-08-05 18:31 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +Substrate - это известный своей гибкостью фреймворк Rust с открытым исходным
Rust фреймворк

2023-08-05 19:07 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +кодом для создания настраиваемых блокчейнов. В то же время VM Cairo специально
здесь лучше "кастомизированных"

2023-08-05 19:09 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +разработана для эффективного создания доказательств достоверности для выполнения
(порядок слов) Cairo VM разработана специально для эффективного создания доказательств достоверного выполнения программ.

2023-08-05 19:14 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +выполнения программы.
Можно немного перефразировать, чтобы не повторяться с предыдущими предложениями: "доказуемости вычислений"

2023-08-05 19:15 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +Присущая фреймворку Substrate модульная природа позволяет разработчикам с
модульность

2023-08-05 19:15 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +легкостью настраивать аппчейн. Никакие предположения не навязываются, что
свой аппчейн

2023-08-07 10:09 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +использовании Cairo для генерации доказательств. Разработчики ничем не
Ничто не ограничивает разрабочиков в том что они могут создать, при этом вычисления остаются доказуемыми, а система наследует безопасность базового чейна — Starknet или Ethereum.

2023-08-07 10:19 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +На начальном этапе Madara будет иметь большое сходство со Starknet, обеспечивая
На начальном этапе Madara будет иметь большое сходство с тем как работает Starknet, что обеспечит совместимость на уровне смарт-контрактов. Большие планы возлагаются на будущую масштабную интеграция Starknet с [Herodotus](https://www.herodotus.dev/), которая позволит использовать [доказательства хранения данных](https://starkware.medium.com/what-are-storage-proofs-and-how-can-they-improve-oracles-e0379108720a) для достижения нового уровня совместимости и взаимодействия контрактов. Интеграция доказательств хранения также позволит аппчейнам на основе Madara получать доступ к состоянию и ликвидности других аппчейнов.

2023-08-07 12:04 UTC, gylman commented on docs/article/ru/madara beast article.md
> +авторизации любых желаемых подсказок кода. Это позволяет аппчейнам
И мне)

2023-08-07 12:08 UTC, gylman commented on docs/article/ru/madara beast article.md
> +   двумя контейнерами исполнения:
https://doc.rust-lang.ru/stable/rust-by-example/crates.html#:~:text=%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%20(%20crate%20)%20%E2%80%94%20%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%86%D0%B0%20%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D1%8F%D1%86%D0%B8%D0%B8,%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BC%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%B0%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%20%D0%B5%D0%B3%D0%BE%20%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D1%8F%D1%86%D0%B8%D0%B5%D0%B9.

2023-08-07 16:41 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +   двумя контейнерами исполнения:
Справедливо

2023-08-07 16:50 UTC, m-kus commented
Он ругается на заголовок в 7 строке
В оригинале

```
<font size=5>_From Massive Cost Reductions to Personalized Control, Discover the
Future of Blockchain Infrastructure_</font>
```

2023-08-07 16:52 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +ограниченниям среды исполнения. С помощью аппчейнов разработчики могут тонко
ограничениям (лишняя н)

2023-08-07 16:53 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +программ. Используя отслеживание состояния и смарт-контракт для проверки этих
Предлагаю везде так, либо везде через дефис (чтобы было единообразно)

2023-08-07 16:55 UTC, m-kus requested changes
Еще общий комментарий: предлагаю везде где дефисы используются (вместо тире) использовать em dash —

2023-08-07 17:06 UTC, m-kus commented on docs/article/ru/madara beast article.md
> +авторизации любых желаемых подсказок кода. Это позволяет аппчейнам
А, ок, наверное имелись в виду хинты Cairo https://book.starknet.io/chapter_9/hints.html (их кстати нет в Cairo 1 :D)
Можно "оптимизаций генератора доказательств"

2023-08-10 09:52 UTC, m-kus approved these changes

2023-08-11 10:52 UTC, tdelabro commented
Hey, @gylman @m-kus I can't judge this one myself haha. Is it ready to be merged?

2023-08-11 10:58 UTC, m-kus commented
Hey :)
It looks fine to me, if @lana-shanghai can also take a look next week and approve — I think it's ok to merge

2023-08-16 09:58 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Разработчики приложений сталкиваются с серьезными проблемами в плане масштабируемости в рамках существующей инфраструктуры блокчейна. Масштабируемость включает в себя два важнейших аспекта: высокую с
убрать "в плане":

Разработчики приложений сталкиваются с серьезными проблемами масштабируемости в рамках существующей инфраструктуры блокчейна.

2023-08-16 10:07 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Разработчики приложений сталкиваются с серьезными проблемами в плане масштабируемости в рамках существующей инфраструктуры блокчейна. Масштабируемость включает в себя два важнейших аспекта: высокую с
Активность сторонних приложений не влияет на пропускную способность, поскольку приложение имеет выделенный блокчейн и не конкурирует за ресурсы, тем самым обеспечивая максимальное удобство пользователям.

2023-08-16 10:16 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +В чейнах общего назначения, таких как Starknet и Ethereum, существует множество мер, направленных на обеспечение доступности сети для всех желающих, что приводит к ограниченным возможностям. С помощь
Блокчейны общего назначения, такие как Starknet и Ethereum, доступны всем пользователям, что в свою очередь приводит к ограниченным возможностям. 

Не нравится функция Cairo VM?

2023-08-16 10:37 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Настраиваемость аппчейнов также позволяет разработчикам работать с функциями, которые в настоящее время недоступны или рискованны в таких средах, как Starknet. Аппчейны предоставят каждой команде авт
С помощью настроек аппчейнов разработчики смогут работать с ранее недоступными или небезопасными функциями на платформах типа Starknet.

2023-08-16 10:40 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Настраиваемость аппчейнов также позволяет разработчикам работать с функциями, которые в настоящее время недоступны или рискованны в таких средах, как Starknet. Аппчейны предоставят каждой команде авт
Аппчейны предоставят любой команде автономию в написании и авторизации приватных вводов данных.

2023-08-16 10:41 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Настраиваемость аппчейнов также позволяет разработчикам работать с функциями, которые в настоящее время недоступны или рискованны в таких средах, как Starknet. Аппчейны предоставят каждой команде авт
Это откроет новые возможности использования, например, применение ончейн KYC без утечки личной информации.

2023-08-16 10:42 UTC, lana-shanghai commented on docs/article/ru/madara beast article.md
> +Давайте посмотрим на взаимодействие различных уровней, обеспечивающих работу аппчейнов, и на то, как на них влияет Madara.
...и на то, какую роль здесь играет Madara.

2023-08-17 18:54 UTC, d-roak commented
@lana-shanghai good to go?

2023-08-17 19:22 UTC, lana-shanghai approved these changes
lgtm

2023-08-17 19:29 UTC, merged