Translation madara beast article.md
keep-starknet-strange/madara pull request #958
Opened 2023-08-02 16:49 UTC by joaopereira12

Please add the labels corresponding to the type of changes your PR introduces:

- Documentation content changes

Resolves: #921 

## What is the new behavior?

madara beast article.md is translated to portuguese.

## Does this introduce a breaking change?

No

2023-08-02 16:52 UTC, d-roak commented
I'll review it

2023-08-03 09:43 UTC, d-roak requested changes

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +## Efeito do Madara na Pilha da Appchain
no Stack para Appchains

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   diferença de estado. Madara oferece a flexibilidade para mudar entre dois
O Madara

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   caixotes de execução,
crates

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   [Blockifier por StarkWare](https://github.com/starkware-libs/blockifier) e
da

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   [Starknet_in_rust por LambdaClass](https://github.com/lambdaclass/starknet_in_rust).
da

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   Independente da crate escolhida, a estrutura subjacente utiliza a Cairo VM. A
do crate escolhido

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +2. **Settlement:** Como um settlement rollup, o estado da appchain do Madara
validity rollup

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +3. **Sequenciamento:** O Madara assume o controlo do processo de sequenciação,
u need to be consistent, pick either "sequencer" or "sequenciamento" through the whole document. Probably the pt alternative is better

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +   Certas appchains podem escolher implementar mempools encriptados para
encriptadas

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +5. **Controlo:** Cada appchain do Madara pode escolher o seu modelo de controlo.
Governança != Controlo, in all paragraph

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +Starknet. Substrate é uma framework do Rust open-source para construir
O Substrate ... em Rust

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +eficientemente para execução de programas. Ao implementar rastreamento de estado
a execução

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +que você incorpore seus protocolo de consenso próprio, funções hash, esquema de
permitindo a incorporação dos teus protocolos de consenso, funções ... 
u started informal and finished formal?

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +assinatura, layout de armazenamento – o que quer que seu aplicativo exija,
armazenamento - independente das necessidades da aplicação, utilizando o Cairo para gerar provas

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +desenvolvedores podem fazer enquanto ainda são demonstráveis, herdando o
fazer, equanto ainda são comprováveis, herdando a segurança da chain ...

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +Inicialmente, Madara terá uma forte semelhança com o Starknet, permitindo a
o Madara ... a Starknet

2023-08-03 09:43 UTC, d-roak commented on docs/content/articles/pt/madara-beast-article.md
> +Encontram-se guardados planos maiores para o futuro à medida que a Starknet se
Existem planos...

2023-08-03 09:45 UTC, d-roak requested changes
double check consistency along the translation

2023-08-16 08:40 UTC, tdelabro commented
@d-roak is this ready to be merged?

2023-08-16 10:47 UTC, d-roak commented
> @d-roak is this ready to be merged?

no, spell-check is not fixed yet, how should we ignore the articles? all in the path (including the en)?

2023-08-16 13:23 UTC, tdelabro commented
@d-roak What is spell check doing exactly? Why is it an issue?

2023-08-16 16:03 UTC, d-roak commented
> @d-roak What is spell check doing exactly? Why is it an issue?

@tdelabro something we add it somewhere in time (before i arrived), that checks the english spelling in stuff... We can add files/paths to be ignored in the `.codespellignore`

2023-08-17 18:53 UTC, merged